### ISSUE TITLE
Block explorer

### ISSUE THREAD

**Issue by axic** [ewasm/testnet#12]
Required feature set:
The block explorer should be able to:
- [x] list blocks
- [x] list transactions
- [ ] show details about transactions
- [ ] show internal calls within transactions
- [x] list accounts
- [x] show details about accounts
- [x] detect wasm contracts and offer the option to display a wast

Some of the open source block explorers:
- https://github.com/ethereumproject/explorer (live: http://etherhub.io/)
- https://github.com/gobitfly/etherchain-light (live: https://light.etherchain.org/)
- https://github.com/etherparty/explorer
- https://github.com/carsenk/explorer (fork of etherparty)
- https://github.com/mix-blockchain/ethereum-explorer
- https://github.com/blk-io/blk-explorer-free
- https://github.com/ethnamed/eth-explorer

@cdetrio's bare minimum explorer features:
account list view (like https://etherscan.io/accounts)
contract code view (like https://etherscan.io/address/0xc0829421c1d260bd3cb3e0f06cfe2d52db2ce315#code)

cf. https://github.com/ewasm/pm/issues/9, https://github.com/ewasm/pm/issues/10, https://github.com/ewasm/ewasm-explorer/issues/6

**Comment by lrettig** [comment]
@zixuanzh update from today:

- figured out routing stuff
- having some trouble with Rinkeby node
- right now I’m using geth, this is a good time to try switching to cpp-ethereum
- haven’t tried spinning up a private network yet with geth
- the challenge is switching from geth to cpp-ethereum
- will talk to Jared or Casey to figure out next steps

@jwasinger update: still trying to get this working.

**Comment by lrettig** [comment]
Update from today's standup. @jwasinger, @hugo-dc, and @cdetrio have been working on the [etherchain-light](https://github.com/gobitfly/etherchain-light) explorer, which is implemented in pure backend JS (it's an express/pug app) and it's roughly at feature parity with the POA explorer that @zixuanzh has been working on. Casey's update:

- switching out backend from parity to cpp
- for launch of testnet we’ll use etherchain-lite since it’s already caught up with the state that ZX got the POA explorer to, roughly at feature parity now
etherchain-lite account list view already based on debug_accountRangeAt vs. the one in POA explorer which is missing accounts in genesis block, ones created by deploying contracts, etc. (it’s based on transactions)
- in order to fix that in POA explorer, it would be a lot more work
- but ZX’s work on POA still useful since for v2 of the explorer which supports internal tx, etc., we’d turn internal tx back on in POA explorer, Pawel has some PRs to support evmc traces which we’d need to support ewasm internal tx
- so we might switch back to POA explorer at this point
- code view, account list view working
- want to add storage dump, WASM to WAST converter/WAST view

**Comment by jwasinger** [comment]
Major remaining features that need to be implemented:
 - [ ] account storage view
 - [ ] wast/wasm code view
 - [ ] ["EWASM Studio"](https://github.com/ewasm/etherchain-light/issues/2)

**Comment by lrettig** [comment]
Update from @cdetrio / @jwasinger / @hugo-dc from this morning's call:

    * On Friday, worked with Hugo to reproduce what Jared got working, etherchain-lite (ECL) block explorer running on cpp-ethereum with `debug_accountRangeAt` RPC method
    * Next step is to improve ECL
        * storage_dump
        * contract_storage: debug_storage_range_at, add to contract view page
        * so you can see both contract and contract storage
        * some frontend stuff to convert hex bytecode to WAST code

**Comment by lrettig** [comment]
Update from @cdetrio / @jwasinger this morning: Testnet explorer/node up at http://13.95.70.101:3000/, launched from ansible scripts. Looks like there are still some broken bits that need to be implemented or removed. Great progress guys.
