### ISSUE TITLE
Precompiles in ewasm

### ISSUE THREAD

**Issue by lrettig** [ewasm/testnet#42]
parent of #39
parent of #37
parent of #14 

List of precompiles:
- [x] identity
- [ ] ecrecover
- [x] sha256
- [x] ripemd160
- [ ] modexp
- [x] ecadd
- [x] ecmul
- [x] ecpairing

**Comment by lrettig** [comment]
Based on today's standup I'm assigning you @hugo-dc. Hugo's update from today (Hugo if this belongs in one of the subissues please let me know, I wasn't sure):

Compile rust VM methods to wasm, getting elliptic curve precompiles implemented in WASM instead of addresses 6, 7, and 8
- Casey started this with the add method
- next instead of using hardcoded values I added the method get_calldatacopy so it should read the values from the input data instead of hardcoded values
- previous test we did is using storageStore, created a test case in ewasm tests to test that it’s working correctly, but after that over the weekend I changed the storageStore method to use return method to return the data instead of storing it
- but had a problem because when I compile this new code everything seems to work fine but I see garbage in the WAST code
- copied code to test case, it’s complaining about YAML formal, but I think it’s the WAST code that’s wrong
- will continue checking that

**Comment by lrettig** [comment]
Question: are these testnet MVP-critical? If so do we need all of the precompiles, or only a subset?

**Comment by lrettig** [comment]
@cdetrio answer to my question from today's standup:

- precompiles in WASM are more for showcasing, not testnet-critical
- too slow anyway until we get WAVM working
- so for testnet it’s the difference between using precompiles as implemented in cpp-ethereum vs. trying to showcase if you’re using a WASM engine then you don’t need to implement the precompiles since they come implemented in WASM

**Comment by lrettig** [comment]
@hugo-dc update from yesterday:

yesterday: changed ecadd contract to return the result instead of storing it, created a test case to test this contract
today: I’ll add the contract to the genesis file in the testnet repo, and more ewasm tests

**Comment by lrettig** [comment]
Hi @hugo-dc how is this coming along? How much work is left? Is it still in progress? Thanks :)

**Comment by hugo-dc** [comment]
Last thingI did about ecadd in Rust was to add it as a precompiled contract in the testnet:
https://github.com/hugo-dc/testnet/tree/ecadd-demo

Then I deployed a contract which calls that precompiled and stores the result, and the result was as expected.

https://github.com/hugo-dc/testnet-demo/tree/ecadd-demo

Next thing I want to do is to run this test agains the ecadd precompiled:

https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stZeroKnowledge/pointAddFiller.json#L239

@cdetrio told me that the rust contract may need some changes in order to pass that test, I'll try to make it pass.

**Comment by lrettig** [comment]
Thanks for the update! 🙏
